# Generated by Django 2.1.7 on 2019-05-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasantri', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationData',
            new_name='Identita',
        ),
    ]
