# Generated by Django 2.1.7 on 2019-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasantri', '0002_auto_20190501_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identita',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='identita',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='identita',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
